# Generated by Django 5.2.4 on 2025-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='normal_ratio_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testtype',
            name='normal_ratio_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testtype',
            name='normal_time_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testtype',
            name='normal_time_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='reference_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='reference_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
