# Generated by Django 5.2.4 on 2025-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_testtype_normal_ratio_max_testtype_normal_ratio_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
