# Generated by Django 5.2.4 on 2025-07-07 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
