# Generated by Django 5.2.4 on 2025-07-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_alter_sample_collection_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_number', models.CharField(blank=True, max_length=20)),
                ('insurance_company', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='sample',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.patient'),
        ),
    ]
